ROLE_MATRIX_SEED = {'Supply Chain Manager': {'slug': 'supply-chain-manager',
                          'title': 'Supply Chain Manager',
                          'onet_code': '11-3071.04',
                          'onet_title': 'Supply Chain Managers',
                          'summary': 'Direct or coordinate production, purchasing, warehousing, distribution, or '
                                     'financial forecasting services or activities to limit costs and improve '
                                     'accuracy, customer service, or safety. Examine existing procedures or '
                                     'opportunities for streamlining activities to meet product distribution needs. '
                                     'Direct the movement, storage, or processing of inventory.',
                          'job_zone': 4,
                          'job_zone_meaning': 'Job Zone Four: Considerable Preparation Needed',
                          'job_zone_education_note': "Most of these occupations require a four-year bachelor's degree, "
                                                     'but some do not.',
                          'top_education_distribution': "Bachelor's Degree (67%); Master's Degree (19%); "
                                                        'Post-Baccalaureate Certificate - awarded for completion of an '
                                                        'organized program of study; designed for people who have '
                                                        'completed a Baccalaureate degree but do not meet the '
                                                        'requirements of academic degrees carrying the title of '
                                                        'Master. (10%)',
                          'resume_keywords': ['forecasting',
                                              'inventory',
                                              'warehousing',
                                              'distribution',
                                              'purchasing',
                                              'supplier negotiation',
                                              'ERP',
                                              'SAP',
                                              'WMS',
                                              'Excel',
                                              'KPI',
                                              'cross-functional coordination'],
                          'likely_interview_topics': ['demand forecasting',
                                                      'inventory optimization',
                                                      'supplier/vendor negotiation',
                                                      'transportation and route decisions',
                                                      'process improvement/KPIs'],
                          'alternate_titles': ['Auto Parts Manager (Automotive Parts Manager)',
                                               'Demand Planning Manager',
                                               'Global Supply Chain Director',
                                               'Global Supply Chain Manager',
                                               'Inventory Control Supervisor',
                                               'Inventory Manager',
                                               'Inventory Supervisor',
                                               'Logistics Supervisor'],
                          'source_urls': {'primary': 'https://www.onetonline.org/link/custom/11-3071.04',
                                          'tech_postings': 'https://www.onetonline.org/link/demand/11-3071.04/In_Demand_11-3071-04.xlsx?fmt=xlsx',
                                          'database': 'https://www.onetcenter.org/database.html',
                                          'kaggle_reference': 'https://www.kaggle.com/datasets/sharmagayatri/job-market-skills-dataset'},
                          'top_skills': [{'name': 'Active Listening',
                                          'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                          'importance': 4.0},
                                         {'name': 'Coordination',
                                          'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                          'importance': 4.0},
                                         {'name': 'Judgment and Decision Making',
                                          'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                          'importance': 4.0},
                                         {'name': 'Monitoring',
                                          'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                          'importance': 4.0},
                                         {'name': 'Reading Comprehension',
                                          'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                          'importance': 4.0},
                                         {'name': 'Speaking',
                                          'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                          'importance': 4.0},
                                         {'name': 'Time Management',
                                          'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                          'importance': 4.0},
                                         {'name': 'Complex Problem Solving',
                                          'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                          'importance': 3.88}],
                          'top_knowledge': [{'name': 'Transportation',
                                             'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                             'importance': 4.48},
                                            {'name': 'Administration and Management',
                                             'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                             'importance': 4.33},
                                            {'name': 'English Language',
                                             'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                             'importance': 4.05},
                                            {'name': 'Economics and Accounting',
                                             'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                             'importance': 3.81},
                                            {'name': 'Customer and Personal Service',
                                             'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                             'importance': 3.76},
                                            {'name': 'Production and Processing',
                                             'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                             'importance': 3.75}],
                          'top_work_activities': [{'name': 'Establishing and Maintaining Interpersonal Relationships',
                                                   'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                                   'importance': 4.43},
                                                  {'name': 'Communicating with Supervisors, Peers, or Subordinates',
                                                   'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                                   'importance': 4.38},
                                                  {'name': 'Making Decisions and Solving Problems',
                                                   'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                                   'importance': 4.38},
                                                  {'name': 'Developing and Building Teams',
                                                   'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                                   'importance': 4.33},
                                                  {'name': 'Analyzing Data or Information',
                                                   'source_url': 'https://www.onetonline.org/link/custom/11-3071.04',
                                                   'importance': 4.2}],
                          'top_tasks': [{'name': 'Determine appropriate equipment and staffing levels to load, unload, '
                                                 'move, or store materials.',
                                         'source_url': 'https://www.onetonline.org/link/custom/11-3071.04'},
                                        {'name': 'Manage activities related to strategic or tactical purchasing, '
                                                 'material requirements planning, controlling inventory, warehousing, '
                                                 'or receiving.',
                                         'source_url': 'https://www.onetonline.org/link/custom/11-3071.04'},
                                        {'name': 'Select transportation routes to maximize economy by combining '
                                                 'shipments or consolidating warehousing and distribution.',
                                         'source_url': 'https://www.onetonline.org/link/custom/11-3071.04'},
                                        {'name': 'Define performance metrics for measurement, comparison, or '
                                                 'evaluation of supply chain factors, such as product cost or quality.',
                                         'source_url': 'https://www.onetonline.org/link/custom/11-3071.04'},
                                        {'name': 'Implement new or improved supply chain processes to improve '
                                                 'efficiency or performance.',
                                         'source_url': 'https://www.onetonline.org/link/custom/11-3071.04'},
                                        {'name': 'Develop procedures for coordination of supply chain management with '
                                                 'other functional areas, such as sales, marketing, finance, '
                                                 'production, or quality assurance.',
                                         'source_url': 'https://www.onetonline.org/link/custom/11-3071.04'}],
                          'top_tech': [{'name': 'Microsoft Excel',
                                        'pct_postings': 20,
                                        'hot': True,
                                        'source_url': 'https://www.onetonline.org/link/demand/11-3071.04/In_Demand_11-3071-04.xlsx?fmt=xlsx'},
                                       {'name': 'Microsoft Office software',
                                        'pct_postings': 16,
                                        'hot': True,
                                        'source_url': 'https://www.onetonline.org/link/demand/11-3071.04/In_Demand_11-3071-04.xlsx?fmt=xlsx'},
                                       {'name': 'SAP software',
                                        'pct_postings': 11,
                                        'hot': True,
                                        'source_url': 'https://www.onetonline.org/link/demand/11-3071.04/In_Demand_11-3071-04.xlsx?fmt=xlsx'},
                                       {'name': 'Microsoft PowerPoint',
                                        'pct_postings': 9,
                                        'hot': True,
                                        'source_url': 'https://www.onetonline.org/link/demand/11-3071.04/In_Demand_11-3071-04.xlsx?fmt=xlsx'},
                                       {'name': 'Inventory management systems',
                                        'pct_postings': 7,
                                        'hot': False,
                                        'source_url': 'https://www.onetonline.org/link/demand/11-3071.04/In_Demand_11-3071-04.xlsx?fmt=xlsx'},
                                       {'name': 'Warehouse management system WMS',
                                        'pct_postings': 6,
                                        'hot': False,
                                        'source_url': 'https://www.onetonline.org/link/demand/11-3071.04/In_Demand_11-3071-04.xlsx?fmt=xlsx'},
                                       {'name': 'Microsoft Outlook',
                                        'pct_postings': 6,
                                        'hot': True,
                                        'source_url': 'https://www.onetonline.org/link/demand/11-3071.04/In_Demand_11-3071-04.xlsx?fmt=xlsx'}],
                          'signals': [{'name': 'Active Listening',
                                       'signal_type': 'Core skill',
                                       'weight': 10,
                                       'comments': None},
                                      {'name': 'Coordination',
                                       'signal_type': 'Core skill',
                                       'weight': 10,
                                       'comments': None},
                                      {'name': 'Judgment and Decision Making',
                                       'signal_type': 'Core skill',
                                       'weight': 10,
                                       'comments': None},
                                      {'name': 'Monitoring',
                                       'signal_type': 'Core skill',
                                       'weight': 10,
                                       'comments': None},
                                      {'name': 'Reading Comprehension',
                                       'signal_type': 'Core skill',
                                       'weight': 10,
                                       'comments': None},
                                      {'name': 'Speaking', 'signal_type': 'Core skill', 'weight': 8, 'comments': None},
                                      {'name': 'Time Management',
                                       'signal_type': 'Core skill',
                                       'weight': 8,
                                       'comments': None},
                                      {'name': 'Complex Problem Solving',
                                       'signal_type': 'Core skill',
                                       'weight': 8,
                                       'comments': None},
                                      {'name': 'Microsoft Excel',
                                       'signal_type': 'In-demand tech',
                                       'weight': 4,
                                       'comments': None},
                                      {'name': 'Microsoft Office software',
                                       'signal_type': 'In-demand tech',
                                       'weight': 4,
                                       'comments': None},
                                      {'name': 'Quantified achievement evidence',
                                       'signal_type': 'Resume quality',
                                       'weight': 8,
                                       'comments': 'Count metrics like %, $, time saved, inventory turns.'},
                                      {'name': 'Role-specific keywords',
                                       'signal_type': 'Resume quality',
                                       'weight': 6,
                                       'comments': 'Use the keyword list from Role Matrix.'}],
                          'mock_questions': ['Tell me about a time you demonstrated demand forecasting in a project, '
                                             'internship, or class assignment relevant to a Supply Chain Manager role.',
                                             'Tell me about a time you demonstrated inventory optimization in a '
                                             'project, internship, or class assignment relevant to a Supply Chain '
                                             'Manager role.',
                                             'Tell me about a time you demonstrated supplier/vendor negotiation in a '
                                             'project, internship, or class assignment relevant to a Supply Chain '
                                             'Manager role.',
                                             'Why are you interested in a Supply Chain Manager role, and how does your '
                                             'background prepare you for it?']},
 'Procurement Analyst': {'slug': 'procurement-analyst',
                         'title': 'Procurement Analyst',
                         'onet_code': '13-1023.00',
                         'onet_title': 'Purchasing Agents, Except Wholesale, Retail, and Farm Products',
                         'summary': 'Purchase machinery, equipment, tools, parts, supplies, or services necessary for '
                                    'the operation of an establishment. Purchase raw or semifinished materials for '
                                    'manufacturing. May negotiate contracts.',
                         'job_zone': 4,
                         'job_zone_meaning': 'Job Zone Four: Considerable Preparation Needed',
                         'job_zone_education_note': "Most of these occupations require a four-year bachelor's degree, "
                                                    'but some do not.',
                         'top_education_distribution': "Bachelor's Degree (65%); High School Diploma - or the "
                                                       "equivalent (for example, GED) (15%); Associate's Degree (or "
                                                       'other 2-year degree) (10%)',
                         'resume_keywords': ['purchase orders',
                                             'bid proposals',
                                             'RFP/RFQ',
                                             'supplier evaluation',
                                             'contract negotiation',
                                             'price analysis',
                                             'compliance',
                                             'Excel',
                                             'SAP',
                                             'vendor management',
                                             'cost savings',
                                             'procurement'],
                         'likely_interview_topics': ['supplier evaluation',
                                                     'contract negotiation',
                                                     'cost analysis',
                                                     'compliance and procurement policy',
                                                     'purchase order / requisition workflow'],
                         'alternate_titles': ['Buyer',
                                              'Contract Administrator (Contract Admin)',
                                              'Contract Analyst',
                                              'Contract Specialist',
                                              'Contractor Buyer',
                                              'Contracts Manager',
                                              'Equipment',
                                              'Supplies',
                                              'and Tools Purchasing Agent',
                                              'Fuel Agent'],
                         'source_urls': {'primary': 'https://www.onetonline.org/link/custom/13-1023.00',
                                         'tech_postings': 'https://www.onetonline.org/link/demand/13-1023.00/In_Demand_13-1023-00.xlsx?fmt=xlsx',
                                         'database': 'https://www.onetcenter.org/database.html',
                                         'kaggle_reference': 'https://www.kaggle.com/datasets/sharmagayatri/job-market-skills-dataset'},
                         'top_skills': [{'name': 'Negotiation',
                                         'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                         'importance': 4.25},
                                        {'name': 'Reading Comprehension',
                                         'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                         'importance': 4.12},
                                        {'name': 'Active Listening',
                                         'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                         'importance': 4.0},
                                        {'name': 'Complex Problem Solving',
                                         'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                         'importance': 4.0},
                                        {'name': 'Speaking',
                                         'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                         'importance': 4.0},
                                        {'name': 'Writing',
                                         'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                         'importance': 4.0},
                                        {'name': 'Active Learning',
                                         'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                         'importance': 3.88},
                                        {'name': 'Critical Thinking',
                                         'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                         'importance': 3.88}],
                         'top_knowledge': [{'name': 'English Language',
                                            'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                            'importance': 4.56},
                                           {'name': 'Law and Government',
                                            'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                            'importance': 4.26},
                                           {'name': 'Customer and Personal Service',
                                            'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                            'importance': 4.22},
                                           {'name': 'Administration and Management',
                                            'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                            'importance': 4.05},
                                           {'name': 'Administrative',
                                            'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                            'importance': 3.63},
                                           {'name': 'Mathematics',
                                            'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                            'importance': 3.37}],
                         'top_work_activities': [{'name': 'Getting Information',
                                                  'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                                  'importance': 4.58},
                                                 {'name': 'Communicating with People Outside the Organization',
                                                  'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                                  'importance': 4.47},
                                                 {'name': 'Communicating with Supervisors, Peers, or Subordinates',
                                                  'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                                  'importance': 4.42},
                                                 {'name': 'Working with Computers',
                                                  'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                                  'importance': 4.32},
                                                 {'name': 'Establishing and Maintaining Interpersonal Relationships',
                                                  'source_url': 'https://www.onetonline.org/link/custom/13-1023.00',
                                                  'importance': 4.21}],
                         'top_tasks': [{'name': 'Monitor and follow applicable laws and regulations.',
                                        'source_url': 'https://www.onetonline.org/link/custom/13-1023.00'},
                                       {'name': 'Purchase the highest quality merchandise at the lowest possible price '
                                                'and in correct amounts.',
                                        'source_url': 'https://www.onetonline.org/link/custom/13-1023.00'},
                                       {'name': 'Formulate policies and procedures for bid proposals and procurement '
                                                'of goods and services.',
                                        'source_url': 'https://www.onetonline.org/link/custom/13-1023.00'},
                                       {'name': 'Prepare purchase orders, solicit bid proposals, and review '
                                                'requisitions for goods and services.',
                                        'source_url': 'https://www.onetonline.org/link/custom/13-1023.00'},
                                       {'name': 'Write and review product specifications, maintaining a working '
                                                'technical knowledge of the goods or services to be purchased.',
                                        'source_url': 'https://www.onetonline.org/link/custom/13-1023.00'},
                                       {'name': 'Analyze price proposals, financial reports, and other data and '
                                                'information to determine reasonable prices.',
                                        'source_url': 'https://www.onetonline.org/link/custom/13-1023.00'}],
                         'top_tech': [{'name': 'Microsoft Excel',
                                       'pct_postings': 27,
                                       'hot': True,
                                       'source_url': 'https://www.onetonline.org/link/demand/13-1023.00/In_Demand_13-1023-00.xlsx?fmt=xlsx'},
                                      {'name': 'Microsoft Office software',
                                       'pct_postings': 25,
                                       'hot': True,
                                       'source_url': 'https://www.onetonline.org/link/demand/13-1023.00/In_Demand_13-1023-00.xlsx?fmt=xlsx'},
                                      {'name': 'Microsoft PowerPoint',
                                       'pct_postings': 15,
                                       'hot': True,
                                       'source_url': 'https://www.onetonline.org/link/demand/13-1023.00/In_Demand_13-1023-00.xlsx?fmt=xlsx'},
                                      {'name': 'Microsoft Outlook',
                                       'pct_postings': 11,
                                       'hot': True,
                                       'source_url': 'https://www.onetonline.org/link/demand/13-1023.00/In_Demand_13-1023-00.xlsx?fmt=xlsx'},
                                      {'name': 'Microsoft Word',
                                       'pct_postings': 8,
                                       'hot': True,
                                       'source_url': 'https://www.onetonline.org/link/demand/13-1023.00/In_Demand_13-1023-00.xlsx?fmt=xlsx'},
                                      {'name': 'SAP software',
                                       'pct_postings': 6,
                                       'hot': True,
                                       'source_url': 'https://www.onetonline.org/link/demand/13-1023.00/In_Demand_13-1023-00.xlsx?fmt=xlsx'},
                                      {'name': 'Microsoft SharePoint',
                                       'pct_postings': 5,
                                       'hot': True,
                                       'source_url': 'https://www.onetonline.org/link/demand/13-1023.00/In_Demand_13-1023-00.xlsx?fmt=xlsx'}],
                         'signals': [{'name': 'Negotiation',
                                      'signal_type': 'Core skill',
                                      'weight': 10,
                                      'comments': None},
                                     {'name': 'Reading Comprehension',
                                      'signal_type': 'Core skill',
                                      'weight': 10,
                                      'comments': None},
                                     {'name': 'Active Listening',
                                      'signal_type': 'Core skill',
                                      'weight': 10,
                                      'comments': None},
                                     {'name': 'Complex Problem Solving',
                                      'signal_type': 'Core skill',
                                      'weight': 10,
                                      'comments': None},
                                     {'name': 'Speaking', 'signal_type': 'Core skill', 'weight': 10, 'comments': None},
                                     {'name': 'Writing', 'signal_type': 'Core skill', 'weight': 8, 'comments': None},
                                     {'name': 'Active Learning',
                                      'signal_type': 'Core skill',
                                      'weight': 8,
                                      'comments': None},
                                     {'name': 'Critical Thinking',
                                      'signal_type': 'Core skill',
                                      'weight': 8,
                                      'comments': None},
                                     {'name': 'Microsoft Excel',
                                      'signal_type': 'In-demand tech',
                                      'weight': 4,
                                      'comments': None},
                                     {'name': 'Microsoft Office software',
                                      'signal_type': 'In-demand tech',
                                      'weight': 4,
                                      'comments': None},
                                     {'name': 'Quantified achievement evidence',
                                      'signal_type': 'Resume quality',
                                      'weight': 8,
                                      'comments': 'Count metrics like %, $, time saved, inventory turns.'},
                                     {'name': 'Role-specific keywords',
                                      'signal_type': 'Resume quality',
                                      'weight': 6,
                                      'comments': 'Use the keyword list from Role Matrix.'}],
                         'mock_questions': ['Tell me about a time you demonstrated supplier evaluation in a project, '
                                            'internship, or class assignment relevant to a Procurement Analyst role.',
                                            'Tell me about a time you demonstrated contract negotiation in a project, '
                                            'internship, or class assignment relevant to a Procurement Analyst role.',
                                            'Tell me about a time you demonstrated cost analysis in a project, '
                                            'internship, or class assignment relevant to a Procurement Analyst role.',
                                            'Why are you interested in a Procurement Analyst role, and how does your '
                                            'background prepare you for it?']},
 'Entry Level Supply Chain Analyst': {'slug': 'entry-level-supply-chain-analyst',
                                      'title': 'Entry Level Supply Chain Analyst',
                                      'onet_code': '13-1081.02',
                                      'onet_title': 'Logistics Analysts',
                                      'summary': 'Analyze product delivery or supply chain processes to identify or '
                                                 'recommend changes. May manage route activity including invoicing, '
                                                 'electronic bills, and shipment tracing.',
                                      'job_zone': 4,
                                      'job_zone_meaning': 'Job Zone Four: Considerable Preparation Needed',
                                      'job_zone_education_note': 'Most of these occupations require a four-year '
                                                                 "bachelor's degree, but some do not.",
                                      'top_education_distribution': "Bachelor's Degree (63.64%); Associate's Degree "
                                                                    '(22.73%)',
                                      'resume_keywords': ['data analysis',
                                                          'inventory',
                                                          'logistics',
                                                          'reporting',
                                                          'supply chain',
                                                          'forecasting',
                                                          'delivery',
                                                          'KPI'],
                                      'likely_interview_topics': ['Excel/data analysis example',
                                                                  'logistics problem-solving',
                                                                  'inventory tracking scenario',
                                                                  'reporting/KPI discussion',
                                                                  'process improvement example'],
                                      'alternate_titles': ['Demand Planning Analyst',
                                                           'Inventory Analyst',
                                                           'Logistics Analyst',
                                                           'Logistics Specialist',
                                                           'Supply Chain Analyst'],
                                      'source_urls': {'primary': 'https://www.onetonline.org/link/summary/13-1081.02',
                                                      'tech_postings': 'https://www.onetonline.org/link/details/13-1081.02',
                                                      'database': 'https://www.onetcenter.org/database.html',
                                                      'kaggle_reference': 'https://www.kaggle.com/datasets/sharmagayatri/job-market-skills-dataset'},
                                      'signals': [{'name': 'Critical Thinking',
                                                   'signal_type': 'Core skill',
                                                   'weight': 10,
                                                   'comments': None},
                                                  {'name': 'Reading Comprehension',
                                                   'signal_type': 'Core skill',
                                                   'weight': 10,
                                                   'comments': None},
                                                  {'name': 'Active Listening',
                                                   'signal_type': 'Core skill',
                                                   'weight': 10,
                                                   'comments': None},
                                                  {'name': 'Complex Problem Solving',
                                                   'signal_type': 'Core skill',
                                                   'weight': 10,
                                                   'comments': None},
                                                  {'name': 'Monitoring',
                                                   'signal_type': 'Core skill',
                                                   'weight': 10,
                                                   'comments': None},
                                                  {'name': 'Speaking',
                                                   'signal_type': 'Core skill',
                                                   'weight': 8,
                                                   'comments': None},
                                                  {'name': 'Systems Analysis',
                                                   'signal_type': 'Core skill',
                                                   'weight': 8,
                                                   'comments': None},
                                                  {'name': 'Systems Evaluation',
                                                   'signal_type': 'Core skill',
                                                   'weight': 8,
                                                   'comments': None},
                                                  {'name': 'Microsoft Excel',
                                                   'signal_type': 'In-demand tech',
                                                   'weight': 4,
                                                   'comments': None},
                                                  {'name': 'Microsoft Office software',
                                                   'signal_type': 'In-demand tech',
                                                   'weight': 4,
                                                   'comments': None},
                                                  {'name': 'Quantified achievement evidence',
                                                   'signal_type': 'Resume quality',
                                                   'weight': 8,
                                                   'comments': None},
                                                  {'name': 'Role-specific keywords',
                                                   'signal_type': 'Resume quality',
                                                   'weight': 6,
                                                   'comments': None}],
                                      'mock_questions': ['Tell me about a time you demonstrated Excel/data analysis '
                                                         'example in a project, internship, or class assignment '
                                                         'relevant to a Entry Level Supply Chain Analyst role.',
                                                         'Tell me about a time you demonstrated logistics '
                                                         'problem-solving in a project, internship, or class '
                                                         'assignment relevant to a Entry Level Supply Chain Analyst '
                                                         'role.',
                                                         'Tell me about a time you demonstrated inventory tracking '
                                                         'scenario in a project, internship, or class assignment '
                                                         'relevant to a Entry Level Supply Chain Analyst role.',
                                                         'Why are you interested in a Entry Level Supply Chain Analyst '
                                                         'role, and how does your background prepare you for it?']}}
